### PR TITLE
Various styling and UX improvements

### PR DESCRIPTION
**Pull request by bkis**
Hi there,
I hope it's okay to send you a PR without discussing the issues up front. At first, I was just fixing these things for myself because I really like using this extension. But then I figured the fixes might actually be an improvement I could contribute.  
Sorry for the 6 commits being squashed in one PR, but my extended commit messages should explain in detail what I did.

Hope this helps,
thanks for this great extension!  
Keep it up! :rocket:

### CODE REVIEW

**Comment by AlexPoilrouge** [comment]
Hello there.

Thanks for the contribution!
I don't usually accept PR about minor styling and appearance tweaks, eventhough I never really polished the UI, but there was clear improvement from yours.

However, I had to add a commit since I reverted back on some changes:
- the 'settings-symbolic' and 'network-vpn-offline-symbolic' icons were not present on my system for some reason… what gnome theme do you use?
- your tweaks on the '.sub-menu-btn' css class caused the menu icons to be out of bound on my system oddly… You're also on gnome 3.36.1, yes?
- also there was a minor bug, when the extension transited from 'LOGGED_OUT' to 'DISCONNECTED' state, the indicator were showing up the wrong color (you missed a 'case' 😅 )

Anyways, thanks a lot for the contribution. 👍 Happy to know you enjoyed from my extension 😀

**Comment by bkis** [comment]
Hey, thanks for merging! I'm on Pop!_OS 19.10 with GNOME Shell 3.34.3 - maybe this is the reason? I tested my changes with a handful of themes, hmm. Well, if the icons aren't present on your end, they shouldn't be used, here :+1:

**Comment by AlexPoilrouge** [comment]
Yes, I believe the fact that you're running on  3.34.3 is the reason. In 3.36 default size of system icons got significantly larger and in fact I add few issues reported to me, when the transition happened, that the large icons were causing visual glitches. I patched it up for the most part, but big values still causes problems (I still struggle with this extension UI API mess…).

So just keep in mind that if you jump to 3.36 there's a high chance that your values might cause the same glitch.

**Comment by bkis** [comment]
I'm looking forward to it :grin:  
Thanks!

**Comment by bkis** [comment]
Hi there! I know this one is closed, but i came back to the symbols choice in the panel. You said your system didn't offer the settings-symbolic` and `network-vpn-offline-symbolic` icons. I searched the Adwaita icon theme a bit (Adwaita is the Gnome default after all, so it should be present, right?) and found two very good replacements which make the panel icon much more "speaking":

image

So when **not** connected, you actually see a **key** in the panel icon. Before it was unclear what the icon even belonged to - there was no connection to networking or VPN at all. And for the settings button:

image

**BTW** I don't know if you made those buttons bigger in your recent release or if it's because of the changes in the Pop!_OS 20.4 theme on my end... it's nothing **I** changed, just saying.

On my system, the related files are here:  
`/usr/share/icons/Adwaita/scalable/emblems/emblem-system-symbolic.svg`  
`/usr/share/icons/Adwaita/scalable/status/network-vpn-no-route-symbolic.svg`
Maybe they work better for you. If you're not interested, that's okay. I'm just gonna keep maintaining my own private version of your great extension with icons I like better :)

Thanks again!

PS: You can check the changed code at https://github.com/bkis/NordVPN-connect

**Comment by AlexPoilrouge** [comment]
Hi.

I'm glad you were able to tweak the extension to fit more to your likings. However, as I mentioned, I don't commit style tweaks anymore, and the icons you mentioned, being part of the default theme, were considered during development, I just knowingly chose to use other ones. Also it is worth noting that, in my current code, the `network-vpn-no-route-symbolic.svg` icon is already in use.

Also, as I mentioned earlier in the thread, gnome 3.36 makes the default style for icon significantly larger. Given that I use the default style whenever I can, your current display of the menu icons seems completely normal.

Cheers!

**Comment by bkis** [comment]
Thanks for your reply! I commented here and didn't create another PR because I wanted to make sure you understand this is just a small follow-up info on the topic. Sorry I didn't realize you already made those icon changes - I just had a OS re-install for 20.04 and installed your extension from gnome.org (without the changes, as they're not released there, yet).  
Thanks again! Keep it up!

**Comment by AlexPoilrouge** [comment]
Sure, no problem.

Actually I meant to say that the `network-vpn-no-route-symbolic.svg` is in use (and has been from the start), but for another purpose (the 'problem' state (STATUS.DAEMON_DOWN, STATUS.LOGGED_OUT,STATUS.NOT_FOUND) along with css class 'panel-status-menu-hbox-problem').

**Pull request merged**
